package com.ktjr.ktwd.groovy.ch13

import groovy.sql.Sql
import org.hsqldb.jdbc.JDBCDataSource
import groovy.text.SimpleTemplateEngine as STE

/**
 * Created by yzy
 * on 2017/10/11.
 */
class DbHelper {


    Sql db

    DbHelper() {
        db = new Sql(new JDBCDataSource(
                database: 'jdbc:hsqldb:mem:testDB',
                user: 'sa',
                password: ''
        ))
    }
    def simpleTemplate = new STE().createTemplate(
            """
                DROP TABLE $name IF EXISTS;
                    CREATE TABLE $name(
                        ${lowname}Id INTEGER GENERATED BY DEFAULT AS IDENTITY, $fields);

            """
    )

    def executeDdl(DataAccessObject dao) {
        def template = simpleTemplate
        def binding = [
                name   : dao.tablename,
                lowname: dao.tablename.toLowerCase(),
                fields : dao.schema.collect {
                    key, val ->
                        "${key.padRight(12)} $val"
                }.join(",\n")
        ]
        def stmt = template.make(binding).toString()
    }
}
