package com.ktjr.ktwd.groovy.ch13

import groovy.sql.Sql

/**
 * Created by yzy
 * on 2017/10/10.
 */
class DbUtil {

    static Sql create(){
        def db = [url:'jdbc:hsqldb:mem:testDB', user:'sa', password:'', driver:'org.hsqldb.jdbc.JDBCDriver']
        def sql = Sql.newInstance(db.url, db.user, db.password, db.driver)

        sql.execute """
            DROP TABLE Athlete IF EXISTS cascade;
            DROP TABLE Record IF EXISTS;
        """

        sql.execute """ 
            CREATE TABLE Athlete (
                athleteId INTEGER GENERATED BY DEFAULT AS IDENTITY,
                firstname VARCHAR(64),
                lastname VARCHAR(64),
                dateOfBirth DATE,
                UNIQUE(athleteId);
        """
    }

    static void main(String[] args) {
        def sql = create()
        def data = [first: 'Ronaldo', last: 'da Costa', birth: '1970-06-07']
        sql.execute """
          INSERT INTO Athlete (firstname, lastname, dateOfBirth)
VALUES (${data.first}, ${data.last}, ${data.birth});
      """
    }
}
